#!/bin/bash

# Make a copy of the hosts file
cp /etc/hosts ~/hosts.new

# Replace localhost IP with 127.0.0.2
sed -i 's/127.*localhost/127.0.0.2 localhost/g' ~/hosts.new

# Add facebook.com entry (or replace if exists)
if grep -q "facebook.com" ~/hosts.new; then
    sed -i 's/.*facebook.com/8.8.8.8 facebook.com/g' ~/hosts.new
else
    echo "8.8.8.8 facebook.com" >> ~/hosts.new
fi

# Copy the modified file back to /etc/hosts
cp -f ~/hosts.new /etc/hosts

# Clean up the temporary file
rm ~/hosts.new